### ISSUE TITLE
Containerized Stage-in with rucio

### ISSUE THREAD

**Issue by rkleinem** [PanDAWMS/pilot3#112]
Hello,

I am not a 100% sure about this but it seems like in a containerized stage-in, `PILOT_RUCIO_SITENAME` is ignored.

Line 921 looks suspicious to me:
https://github.com/PanDAWMS/pilot3/blob/569c213adbc67d3cef0de17f0e53efe67063c561/pilot/user/atlas/container.py#L916-L921

**Comment by PalNilsson** [comment]
Lines 918-920 should have been out-commented as they are not needed, but site name was lost. I will fix it. Thanks
