### ISSUE TITLE
Unnecessary stage-out file existence verification with wrong wan domain

### ISSUE THREAD

**Issue by vokac** [PanDAWMS/pilot3#31]
In the rucio copytool pilot explicitly verify existence of uploaded file during stage-out https://github.com/PanDAWMS/pilot3/blob/ab2d317630a6f71c03929984b333a329ed9806dd/pilot/copytool/rucio.py#L43-L52
but this `exists` by default use "wan" domain (potentially different storage doors). This can lead to unexpected / surprising behavior, because site administrators may not expect connection from local jobs via external storage doors. Also this validation seems to be redundant to the rucio upload code https://github.com/rucio/rucio/blob/bea5ec5901b3d402463c737f9d938211170dd5c3/lib/rucio/client/uploadclient.py#L676-L699

**Comment by PalNilsson** [comment]
Alexey will be back from holidays next week, and will look at it then.

**Comment by anisyonk** [comment]
so, what is the outcome?

we keep stage-out file validation check at pilot side using rucio API, but simply force `rsemanager.exists` to use LAN protocol(s) (domain='lan')  instead of default `wan`?

**Comment by PalNilsson** [comment]
Yes, I think that's best. Thanks Alexey
