### ISSUE TITLE
support for batch job ID for kubernetes

### ISSUE THREAD

**Issue by rptaylor** [PanDAWMS/pilot3#51]
Addressing https://github.com/PanDAWMS/pilot3/issues/50  will show us the right node names on k8s, but then we won't have the batch job IDs (which are currently reported as the node name).

Normally a job would display `Batch ID` under "key job parameters" and `batchid` under "all job parameters", for example:
https://bigpanda.cern.ch/job?pandaid=5564946734

However on kubernetes this is not detected:
https://bigpanda.cern.ch/job?pandaid=5565880899

Just as in https://github.com/PanDAWMS/pilot3/issues/50 we can expose the batch ID as any environment variable. 

I noticed https://github.com/PanDAWMS/pilot3/blob/master/pilot/util/auxiliary.py#L114  so I think we would hope to extend this so that the batch ID of a k8s job can be detected from an environment variable.
Note that pods already have a number of  `KUBERNETES_*` env vars that are internally defined by kubernetes so I think we should choose something distinct from that, for example `K8S_JOB_ID`.  I can work with Fernando to standardize this on all jobs submitted to k8s by Harvester.  What do you think @PalNilsson ?  Thanks.

**Comment by PalNilsson** [comment]
K8S_JOB_ID sounds good to me. I can add it to the dictionary you mention ('K8S_JOB_ID': 'Kubernetes').

**Comment by rptaylor** [comment]
Thanks @PalNilsson , I have asked Fernando to set this up on the Harvester side, same for the other issue. I'll keep an eye out for the next pilot release, let me know if you need anything else.
