### ISSUE TITLE
exception caught when get_proxy tries to write to proxy file

### ISSUE THREAD

**Issue by rptaylor** [PanDAWMS/pilot3#52]
Hi @PalNilsson 

I noticed
```
2022-08-24 16:18:58,609 | INFO     | pilot.util.https                 | get_curl_command          | request: curl -sS --compressed --connect-timeout 100 --max-time 120 --capath /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/etc/grid-security-emi/certificates --cert /proxy/x509up_u25606_prod --cacert /proxy/x509up_u25606_prod --key /proxy/x509up_u25606_prod -H 'User-Agent: pilot/3.3.4 (69) (Python 3.8.13; Linux x86_64)' -H 'Accept: application/json' --config /pilotdir/PanDA_Pilot3_4235_1661356884/curl_getProxy.config https://aipanda057.cern.ch:25443/server/panda/getProxy
2022-08-24 16:18:58,609 | INFO     | pilot.util.container             | print_executable          | executing command: curl -sS --compressed --connect-timeout 100 --max-time 120 --capath /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/etc/grid-security-emi/certificates --cert /proxy/x509up_u25606_prod --cacert /proxy/x509up_u25606_prod --key /proxy/x509up_u25606_prod -H 'User-Agent: pilot/3.3.4 (69) (Python 3.8.13; Linux x86_64)' -H 'Accept: application/json' --config /pilotdir/PanDA_Pilot3_4235_1661356884/curl_getProxy.config https://aipanda057.cern.ch:25443/server/panda/getProxy
2022-08-24 16:19:00,645 | ERROR    | pilot.util.proxy                 | get_proxy                 | exception caught:
[Errno 30] Read-only file system: '/proxy/x509up_u25606_prod',
traceback: Traceback (most recent call last):
  File "/pilotdir/atlas_FVvipxe6/pilot3/pilot/util/proxy.py", line 87, in get_proxy
    _file = os.open(proxy_outfile_name, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
OSError: [Errno 30] Read-only file system: '/proxy/x509up_u25606_prod'
```

On k8s systems the $X509_USER_PROXY file is a mounted secret volume that (like all k8s mounted secrets) is read-only in the pod. It is regularly refreshed by Harvester so jobs always see a recent proxy.

It looks like the get_proxy function tries to open the proxy for writing:
https://github.com/PanDAWMS/pilot3/blob/master/pilot/util/proxy.py#L85

Incidentally the ownership and permission of a mounted secret in k8s have to be like this:
```
-rw-r--r--. 1 root localuser 11958 Aug 24 20:43 x509up_u25606_pilot
-rw-r--r--. 1 root localuser 12596 Aug 24 20:43 x509up_u25606_prod
```
which is fine since there are no other users in the pod, but can cause compatibility issues if applications assume/expect a traditional multi-user environment.

Is the exception an issue, or just cosmetic?  Even if the latter it would be nice to avoid it always happening. Perhaps the pilot could only try to open the proxy file for writing if it does not exist?

Thanks!

**Comment by PalNilsson** [comment]
Hi Ryan,
Can you please forward the Panda ID for that? I'd like to see exactly what happened (and which pilot version you are using). In the case the proxy has expired, the pilot will download a new proxy so it will certainly need to open the file in write mode. The other case is for payload proxies in user jobs, which are also downloaded by the pilot and also needs to be written. Check if the proxy actually had expired. If these mechanisms are not desired on kubernetes, we need some logic to turn them off.
Cheers, Paul

**Comment by rptaylor** [comment]
Hi Paul,

It seemed to be a dev pilot running on our prod cluster, does that indicate it is a new feature that will arrive in the prod pilot soon?
```
pilotUrlOpt=--piloturl http://cern.ch/atlas-panda-pilot/pilot3-dev.tar.gz

2022-08-25 18:00:20,689 [wrapper] pandaids: 5575013890
```
I can send the whole log file.

This job executed only 40 minutes before I checked the proxy, it had > 95 hours remaining. Harvester refreshes it regularly and the same proxy is used by all jobs on the cluster, so if there were a problem with the proxy there would have been widespread failures. However, I checked every job on the cluster and only 5 jobs had this message.  Actually all of them were dev pilots according to `pilotUrlOpt=--piloturl http://cern.ch/atlas-panda-pilot/pilot3-dev.tar.gz`

The pilot will not be able to update or write a proxy file, unless it places it in a different location from the provided $X509_USER_PROXY.

Thanks!

**Comment by PalNilsson** [comment]
Hi Ryan, sorry about the delay. Can you please try this version instead?
http://cern.ch/atlas-panda-pilot/pilot3-3.3.4.86.tar.gz
It should have a fix for read-only file systems.
Cheers, Paul

**Comment by rptaylor** [comment]
Hi Paul,

Thanks, I am not sure how though. Is there a CRIC parameter to use a different pilot URL?
https://atlas-cric.cern.ch/atlas/pandaqueue/detail/CA-VICTORIA-K8S-TEST-T2/

-rt

Ryan Taylor
Research Computing Specialist
Research Computing Services, University Systems
University of Victoria

________________________________________

**Comment by PalNilsson** [comment]
Hi,
I've updated it for you. In the "Associated Params" section you just click "Add Param" and then add "pilot_url" + a value.
Cheers, Paul

**Comment by PalNilsson** [comment]
Just a note: it's better that we use fixed pilot versions, like 3.3.4.86, than the generic pilot3-dev version since that might not be stable (as you actually saw). pilot3-dev will still be used for the automatic RC test jobs, but if you send a normal test job to the queue, it should use the 3.3.4.86 version. RC jobs arrive very slowly and I don't see any such jobs since yesterday.

**Comment by PalNilsson** [comment]
Hi @rptaylor I have updated the pilot version in CRIC (close to final version), but I don't see any jobs running
http://apfmon.lancs.ac.uk/q/CA-VICTORIA-K8S-TEST-T2
Can you please check?
Cheers, Paul

**Comment by rptaylor** [comment]
The dev cluster was in scheduled downtime because I was rebuilding it.  Should be running again now.

> it's better that we use fixed pilot versions
Do you mean temporarily for cases like this to confirm a specific issue is fixed, or in general? If the latter surely we will forget about the version in CRIC and it will get out of date.

**Comment by PalNilsson** [comment]
If you use the default dev pilot, it means that the wrapper is downloading the pilot3-dev.tar.gz tarball. This one is inherently unstable, ie risky to use for anything but pure tests. A fixed version will have the version number in the file name, like pilot3-3.3.3.1.tar.gz. I will only create those files for release or to test specific things, like on your queue. In fact, we're just now in the process of moving to use fixed pilot versions also for production since we're using the pilot in three different experiments, and they will in general not care about changes only relevant for the others.
I updated the version on your queue yesterday to the latest stable version, 3.3.4.114, looks good as far as I can see. If there's a need to download a proxy, it will do so to the work directory which will be writable..

**Comment by rptaylor** [comment]
Okay sounds good, as long as I don't have to do or remember anything to make sure the right pilot version is used. I guess I will just leave the pilot_url option alone and you can change it as needed.

Thanks for the fix! I suppose this can be closed then.
