### ISSUE TITLE
Hardcoded directory for store_jobids

### ISSUE THREAD

**Issue by ptrlv** [PanDAWMS/pilot3#54]
The pandaIDs file is written to hardcoded 'pilot3' directory:
https://github.com/PanDAWMS/pilot3/blob/master/pilot/control/job.py#L1162

For atlas this is fine, for Rubin the args.sourcedir is pilot3-3.3.3.1 (for example). This gives error whe writing since pilot3 doesn't exist.
2022-09-23 14:04:35,102 | WARNING  | pilot.control.job                | store_jobid               | exception caught while trying to store job id: error code: 1303, message: Failed during file handling
details: [Errno 2] No such file or directory: '/home/data/tmp/489746.1.grid7/rubin_IARJjaG8/pilot3/pandaIDs.out'

**Comment by PalNilsson** [comment]
Ok, to be addressed in the next pilot version.

**Comment by PalNilsson** [comment]
Peter, can you set some env variable, say PANDA_PILOT_SOURCE, where you untar the source? I tried using args.sourcedir but it looks like it's not always the source dir.. Maybe cleaner with an env var?

**Comment by ptrlv** [comment]
Yes, can do that. We'd extract the pilot, detect the extracted directory name, then set PANDA_PILOT_SOURCE to this location. eg. PANDA_PILOT_SOURCE=/home/data/tmp/489746.1.grid7/rubin_IARJjaG8/pilot3-3.3.3.1

**Comment by PalNilsson** [comment]
OK supported in latest dev pilot. Let me know when it can be tested, thanks.

**Comment by ptrlv** [comment]
I've put this in the rubin wrapper. I suggest you deploy this and use existing behavior if PANDA_PILOT_SOURCE does not exist.

**Comment by PalNilsson** [comment]
Release (with this fix) is in progress. Closing the issue.
